name: Latest YouTube Videos
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update README with YouTube videos
    runs-on: ubuntu-latest
    permissions:
      contents: write # 明确赋予读写权限
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE-FEED"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCujLSjyi6e-Z3OdEnbex9hg"
          max_post_count: 5
